CXX = g++
PATHI = ./ijRenderEngine/include
PATHE = ./ijRenderEngine/extern
PATHSRC = ./ijRenderEngine/src

pipeline.o:${PATHSRC}/pipeline.cpp ${PATHI}/pipeline.h 
	$(CXX) -c ${PATHSRC}/pipeline.cpp -I ${PATHI} -I ${PATHE}
	
Utilities.o: ${PATHSRC}/Utilities.cpp ${PATHI}/Utilities.h 
	$(CXX) -c ${PATHSRC}/Utilities.cpp -I ${PATHI} -I ${PATHE}
	
Main.o:${PATHSRC}/Main.cpp
	$(CXX) -c ${PATHSRC}/Main.cpp -I ${PATHI} -I ${PATHE}
	
all:main.o pipeline.o Utilities.o
	$(CXX) Main.o pipeline.o Utilities.o -o demo.exe -lgdi32
	
clean:
		rm -f *.o *.exe 